package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE,
	GO_TO_REGISTRATION,
	GO_TO_VIEW_NEWS,
	DO_SIGN_IN,
	DO_REGISTRATION,
	DO_SIGN_OUT,
	CHANGE_LOCAL,
	GO_TO_AUTHENTICATION,
	GO_TO_ERROR_PAGE,
	GO_TO_ACCOUNT,
	DO_UPDATE_ACCOUNT,
	DO_UPDATE_PASSWORD,
	DO_DELETE_ACCOUNT,
	GO_TO_ADMIN_MENU,
	GO_TO_LIST_USERS,
	GO_TO_FILE_SYSTEM,
	DO_UPLOAD_FILE,
	DO_UPDATE_FILE,
	DO_DELETE_FILE,
	DO_UPDATE_ROLE
}
