package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE,
	GO_TO_REGISTRATION,
	GO_TO_VIEW_NEWS,
	DO_SIGN_IN,
	DO_REGISTRATION,
	DO_SIGN_OUT,
	CHANGE_LOCAL,
	GO_TO_AUTHENTICATION,
	GO_TO_ERROR_PAGE
}
